[CmdletBinding()]
param(
  [switch]$Check
)

$ErrorActionPreference = 'Stop'

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$sourcePath = Join-Path $repositoryRoot 'src\ChronoKit.pas'
$referencePath = Join-Path $repositoryRoot 'docs\API-Reference.md'
$source = Get-Content -LiteralPath $sourcePath -Raw
$interfaceEnd = $source.IndexOf("`nimplementation")
if ($interfaceEnd -lt 0) {
  throw 'Could not locate ChronoKit interface declarations.'
}

$interfaceSource = $source.Substring(0, $interfaceEnd)
$classMatch = [regex]::Match($interfaceSource,
  '(?ms)^  TChronoKit = class.*?^  end;$')
if (-not $classMatch.Success) {
  throw 'Could not locate the TChronoKit declaration.'
}

$publicStart = $classMatch.Value.IndexOf("  public")
if ($publicStart -lt 0) {
  throw 'Could not locate TChronoKit public declarations.'
}

$publicDeclarations = $classMatch.Value.Substring($publicStart)
$declarationPattern = [regex]::new(
  '(?ms)^\s{4}class\s+(?<kind>function|procedure)\s+(?<name>[A-Za-z]\w*)\b.*?\bstatic;')
$matches = $declarationPattern.Matches($publicDeclarations)
if ($matches.Count -eq 0) {
  throw 'No public TChronoKit declarations were found.'
}

$methods = @()
$missingDocumentation = @()
$cursor = 0
$lastComment = ''
foreach ($match in $matches) {
  $leading = $publicDeclarations.Substring($cursor, $match.Index - $cursor)
  $commentStart = $leading.LastIndexOf('{')
  if ($commentStart -ge 0) {
    $lastComment = $leading.Substring($commentStart)
  }

  $suffixLength = [Math]::Min(160,
    $publicDeclarations.Length - ($match.Index + $match.Length))
  $suffix = $publicDeclarations.Substring($match.Index + $match.Length,
    $suffixLength)
  $isDeprecated = $suffix -match '^\s*deprecated\b'
  $declaration = [regex]::Replace($match.Value.Trim(), '\s+', ' ')
  $commentText = [regex]::Replace($lastComment, '[{}]', '')
  $commentText = [regex]::Replace($commentText, '\s+', ' ').Trim()
  $hasUsefulDocumentation = ($lastComment -match
    '(?i)@description|@returns|@raises|@see|@example|docs/') -or
    ($commentText.Length -ge 24)

  if (-not $isDeprecated -and -not $hasUsefulDocumentation) {
    $missingDocumentation += $declaration
  }

  if (-not $isDeprecated) {
    $summary = ''
    $descriptionMatch = [regex]::Match($lastComment,
      '(?is)@description\s+(?<summary>.*?)(?=\s+@(param|returns|raises|usage|warning|example|see)\b|\})')
    if ($descriptionMatch.Success) {
      $summary = $descriptionMatch.Groups['summary'].Value
    }
    if ([string]::IsNullOrWhiteSpace($summary)) {
      $summary = 'See the declaration contract and linked executable example.'
    }
    $summary = [regex]::Replace($summary, '\s+', ' ').Trim()
    $summary = $summary.Replace('|', '\|')
    $methods += [pscustomobject]@{
      Name = $match.Groups['name'].Value
      Declaration = $declaration.Replace('|', '\|')
      Summary = $summary
    }
  }
  $cursor = $match.Index + $match.Length
}

if ($missingDocumentation.Count -gt 0) {
  $missingList = $missingDocumentation -join [Environment]::NewLine
  throw "Preferred declarations need a contract, error rule, or example link:`n$missingList"
}

$lines = @(
  '# ChronoKit-FP API reference',
  '',
  '> Generated from public `TChronoKit` declaration comments by `tools/GenerateApiReference.ps1`. Do not edit this file manually.',
  '',
  'Search this page by task or method name. For a guided introduction, start with the [learning path](Learning-Path.md).',
  '',
  '## Preferred TChronoKit methods',
  '',
  '| Method | Declaration | Contract summary |',
  '|---|---|---|'
)
foreach ($method in $methods) {
  $lines += "| ``$($method.Name)`` | ``$($method.Declaration)`` | $($method.Summary) |"
}
$content = ($lines -join [Environment]::NewLine) + [Environment]::NewLine

if ($Check) {
  if (-not (Test-Path -LiteralPath $referencePath)) {
    throw 'docs/API-Reference.md is missing. Run tools/GenerateApiReference.ps1.'
  }
  $existing = Get-Content -LiteralPath $referencePath -Raw
  if ($existing -cne $content) {
    throw 'docs/API-Reference.md is stale. Run tools/GenerateApiReference.ps1 and commit the result.'
  }
  Write-Host "API reference is current for $($methods.Count) preferred declarations."
  exit 0
}

Set-Content -LiteralPath $referencePath -Value $content -NoNewline
Write-Host "Generated API reference for $($methods.Count) preferred declarations."
